name: 'eks-charts'

on:
  push:
    branches:
    - develop
    paths:
    - 'stable/**'
    - '.github/workflows/**'

jobs:
  charts:
    name: 'eks-charts'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: 'asdf:install'
      uses: asdf-vm/actions/install@v1.1.0

    - name: 'eks-charts:lint'
      run: helm lint stable/*

    - name: 'charts:releaser'
      uses: helm/chart-releaser-action@v1.2.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: github.ref == 'refs/heads/main'

    - name: 'charts:success'
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: ${{ secrets.SLACK_CHANNEL }}
        status: SUCCESS
        color: good

    - name: 'charts:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: ${{ secrets.SLACK_CHANNEL }}
        status: failure
        color: danger
